name: Staging CI CD workflow
on:
  push:
    branches:
      - staging
jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn run build
      - name: tar the the build folder
        run: tar -czf dist.tar.gz ./dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist.tar.gz
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Copy ssh-key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H sitedoctruyen.id.vn > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/known_hosts
      - name: Conpy artifact to server
        run: |
          scp -i ~/.ssh/id_rsa dist.tar.gz triuq@sitedoctruyen.id.vn:~/doctruyen/fe
      - name: deploy in remote server
        run: |
          ssh triuq@sitedoctruyen.id.vn << 'EOF'
          rm -rf ~/doctruyen/fe
          mkdir -p ~/doctruyen/fe
          cd ~/doctruyen/fe
          tar -xzf dist.tar.gz
          rm -rf dist.tar.gz
          sudo systemctl restart nginx
          EOF
